"""Send analysis emails via SMTP."""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


def _markdown_to_html(text: str) -> str:
    """Minimal markdown-to-HTML conversion for Claude's output.

    Handles headers, bold, bullet points, and paragraphs.
    """
    import re

    lines = text.split("\n")
    html_lines = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            html_lines.append("<br>")
            continue

        # Headers
        if stripped.startswith("### "):
            html_lines.append(f"<h3>{stripped[4:]}</h3>")
        elif stripped.startswith("## "):
            html_lines.append(f"<h2>{stripped[3:]}</h2>")
        elif stripped.startswith("# "):
            html_lines.append(f"<h1>{stripped[2:]}</h1>")
        # Bullet points
        elif stripped.startswith("- ") or stripped.startswith("* "):
            content = stripped[2:]
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
            html_lines.append(f"<li>{content}</li>")
        # Numbered lists
        elif re.match(r"^\d+\.\s", stripped):
            content = re.sub(r"^\d+\.\s", "", stripped)
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
            html_lines.append(f"<li>{content}</li>")
        else:
            # Bold
            line_html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", stripped)
            html_lines.append(f"<p>{line_html}</p>")

    return "\n".join(html_lines)


def send_email(
    symbol: str,
    quarter: int,
    year: int,
    analysis: str,
    email_config: dict,
    smtp_password: str,
) -> bool:
    """Send an earnings analysis email.

    Returns True on success, False on failure.
    """
    subject = f"Earnings Analysis: {symbol} Q{quarter} {year}"

    body_html = f"""
    <html>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; color: #333;">
        <h1 style="border-bottom: 2px solid #2563eb; padding-bottom: 10px; color: #1e40af;">
            {symbol} — Q{quarter} {year} Earnings Call Analysis
        </h1>
        <div style="line-height: 1.6;">
            {_markdown_to_html(analysis)}
        </div>
        <hr style="margin-top: 30px; border: none; border-top: 1px solid #ddd;">
        <p style="color: #888; font-size: 12px;">
            Generated by Earnings Call In Your Mailbox — powered by Claude
        </p>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = email_config["sender"]
    msg["To"] = email_config["recipient"]

    # Plain text fallback
    msg.attach(MIMEText(f"{subject}\n\n{analysis}", "plain"))
    # HTML version
    msg.attach(MIMEText(body_html, "html"))

    try:
        with smtplib.SMTP(email_config["smtp_host"], email_config["smtp_port"]) as server:
            server.starttls()
            server.login(email_config["sender"], smtp_password)
            server.sendmail(email_config["sender"], email_config["recipient"], msg.as_string())

        logger.info("Email sent: %s", subject)
        return True

    except smtplib.SMTPException as e:
        logger.error("Failed to send email for %s: %s", symbol, e)
        return False
